name: fetch_mcp
description: MCP server
version: 1.0.0
publish_to: none
repository: https://github.com/jhsware/dart_dev_mcp

environment:
  sdk: ^3.9.3
resolution: workspace

dependencies:
  jhsware_code_shared_libs:
    path: ../shared_libs
  mcp_dart:
    path: ../../../mcp_dart
  html: ^0.15.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
